// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Curates the 'Hot Deals' feed using AI to display relevant and trustworthy promotions.
 *
 * - curateHotDeals - A function that curates the hot deals feed.
 * - HotDeal - Represents a single hot deal with a title, description, and confidence score.
 * - CurateHotDealsInput - The input type for the curateHotDeals function.
 * - CurateHotDealsOutput - The return type for the curateHotDeals function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const HotDealSchema = z.object({
  title: z.string().describe('The title of the promotion.'),
  description: z.string().describe('A detailed description of the promotion.'),
});

export type HotDeal = z.infer<typeof HotDealSchema>;

const CurateHotDealsInputSchema = z.object({
  deals: z.array(HotDealSchema).describe('An array of hot deals to curate.'),
});

export type CurateHotDealsInput = z.infer<typeof CurateHotDealsInputSchema>;

const CurateHotDealsOutputSchema = z.array(
  z.object({
    title: z.string().describe('The title of the promotion.'),
    description: z.string().describe('A detailed description of the promotion.'),
    confidence: z
      .number()
      .min(0)
      .max(1)
      .describe(
        'A confidence score (0 to 1) indicating the relevance and trustworthiness of the deal.'
      ),
  })
);

export type CurateHotDealsOutput = z.infer<typeof CurateHotDealsOutputSchema>;

export async function curateHotDeals(input: CurateHotDealsInput): Promise<CurateHotDealsOutput> {
  return curateHotDealsFlow(input);
}

const curateHotDealsPrompt = ai.definePrompt({
  name: 'curateHotDealsPrompt',
  input: {schema: CurateHotDealsInputSchema},
  output: {schema: CurateHotDealsOutputSchema},
  prompt: `You are an expert curator of online deals and promotions. Your task is to evaluate a list of "hot deals" and assign each a confidence score based on its relevance and trustworthiness. You should also filter out any deals that appear to be scams or are not genuinely valuable to users.

Here are the deals to evaluate:

{{#each deals}}
  - Title: {{{this.title}}}
    Description: {{{this.description}}}
{{/each}}

For each deal, provide a confidence score between 0 and 1. A score of 1 indicates high relevance and trustworthiness, while a score of 0 indicates a likely scam or irrelevant promotion. Return an array of deals with the confidence scores.
`,
});

const curateHotDealsFlow = ai.defineFlow(
  {
    name: 'curateHotDealsFlow',
    inputSchema: CurateHotDealsInputSchema,
    outputSchema: CurateHotDealsOutputSchema,
  },
  async input => {
    const {output} = await curateHotDealsPrompt(input);
    return output!;
  }
);
